### ISSUE TITLE
Write unit tests for important tasks

### ISSUE THREAD

**Issue by gameFace22** [Hackademic/hackademic#113]
We need to start writing unit tests for the important tasks first and need to extend it for other jobs in future. 
Our priority would be,
1) Adding Challenges
2)Adding Users 
3)Admin page
4)Challeges. 

Please add your thoughts also :)

**Comment by northdpole** [comment]
continuation of #58, the branch for unit tests is northdpole/unit_tests , we also need:

5) Advanced scoring
6) adding and viewing articles
7) assigning users to classes
8) assign challenges to classes
9) search

**Comment by northdpole** [comment]
partly solved, see the hacakdemic_devtests folder for skeleton functional tests and also part of the summer code sprint proposal linked in #154
