### ISSUE TITLE
404 page with information disclosure

### ISSUE THREAD

**Issue by gameFace22** [Hackademic/hackademic#119]
Generally 404 pages doesn't disclose the server information,right? 
This is not a big issue with our app. But still,considering safe security practices,should it be still included?

**Comment by pchaigno** [comment]
Could you show an example (screenshot)?

**Comment by gameFace22** [comment]
![snapshot52](https://cloud.githubusercontent.com/assets/7415260/5597891/478c2c2e-92d1-11e4-9704-47b48e0f915b.png)
This is not a big issue. But still,considering security practices(like removing installation files) we could probably remove the server info.

**Comment by pchaigno** [comment]
That depends on the configuration of your web server (Apache in your case).
It's not a problem with Hackademic so I'm going to close this issue.

**Comment by northdpole** [comment]
let's create our own custom  .htaccess file.. That way we could provide secure configuration ourselves (opening ticket)
