### ISSUE TITLE
False error message when user account does not exist

### ISSUE THREAD

**Issue by NullArgument** [Hackademic/hackademic#127]
If you enter a Username/Password combination that does not exists in the default login form, you get an "Account not activated" message which is not true.

![screen](https://cloud.githubusercontent.com/assets/8127545/5605651/f50e5b1c-940f-11e4-9aee-0fb16d8828d4.png)

**Comment by pchaigno** [comment]
We may have to change the message to be more generic (`not activated or inexistent`) but I don't think that's really a problem.
I think it's better if we don't say which usernames are valid.

**Comment by NullArgument** [comment]
@pchaigno 
I agree with you, it's not really a problem and non-disclosure of usernames is a good security practice.

However, I believe the best message that fits here is "Wrong username and/or password", it is the common message that almost all sites use.

**Comment by NullArgument** [comment]
Fixed in e82a8fd61e6666c85eececf044d44cb1bac4f874
