### ISSUE TITLE
Add Travis CS integration

### ISSUE THREAD

**Issue by DinisCruz** [Hackademic/hackademic#131]
Now that you are starting to add UnitTests(https://github.com/Hackademic/hackademic/issues/58), it will make a massive difference if you add TravisCI support 

see http://docs.travis-ci.com/user/languages/php/ and https://github.com/o2platform/atom-coffee-repl/issues/1

**Comment by pchaigno** [comment]
:+1: (we already mentioned it in emails if I remember correctly)

**Comment by northdpole** [comment]
Started working on this, we need
#  automated deploy/install
# to check if travis works with web driver and if it doesn't find a way to make it connect to a remote web # driver
# finish the tests

if anyone wants to help drop a line

**Comment by northdpole** [comment]
merging with #154 it's part of that summer code sprint proposal
