### ISSUE TITLE
Start hackademic using npm

### ISSUE THREAD

**Issue by DinisCruz** [Hackademic/hackademic#132]
I know that there are some 'php friendly' install instructions on the home page, but I mainly use node these days, and it would be great if all I had to do to run hackademic would be to:

```sh
git clone git@github.com:Hackademic/hackademic.git
cd hackademic
npm start
````

Making this happen will also help with https://github.com/Hackademic/hackademic/issues/131 (and unit tests writing)

**Comment by northdpole** [comment]
I thought node is used for server side js. It's not possible to run php on node, is it?

**Comment by DinisCruz** [comment]
Well npm is a great package/dependency manager, which also makes it easy to run scripts during builds (and that is even before getting into Grunt or Gulp).

What I'm thinking of is to make it easy to download and install the multiple dependencies, followed by applying any required config options

**Comment by pchaigno** [comment]
We're now using composer ;)
