### ISSUE TITLE
swap the default db to SQLite

### ISSUE THREAD

**Issue by northdpole** [Hackademic/hackademic#134]
Dinis' comments gave me the idea of switching our main db from mysql to sqlite.[1]
In the installer we can keep mysql for those who prefer it but add sqlite as the first option.
It seems that we get several advantages over mysql.

* It's embedded, as in we can package everything in a .phar  which runs out of the box without the need for an external db.

* The user doesn't need to have mysql installed, a simple apache,ngix or any php-capable web server will do.

* The requirements on disk and memory go down by quite a bit. Especially since we're planning on introducing the sandbox which is supposed to be quite heavy on memory.

It seems more suitable for our small platform since we don't get that many hits/day to justify a separate database server. 

After some discussion @the mailing list we think this is a good idea

**Comment by lucif3rr** [comment]
Is this currently in progress ? May be we can add the exact data now we are entering into mysql database into some file called **hackademic.db** and then we can place it in the root directory. Then we can modify the database request to access the data from the new db.

I haven't personally looked in to how much data we are handling but from my past experience with sqlite, if we are handling very large amount of data, I don't think sqlite is a good option as it will lag like hell. But I think we are not dealing with a high amount data so I guess sqlite will be a good option.

**Comment by northdpole** [comment]
I tried it in the weekend. I ran into the following: If apache and php have write and read access to the db file then what stops people from downloading the file locally ?

**Comment by pchaigno** [comment]
> I tried it in the weekend. I ran into the following: If apache and php have write and read access to the db file then what stops people from downloading the file locally ?

Apache configuration. `www-data` should be able to write and read the db file but it shouldn't be in a location accessible to the users through the web server.
