### ISSUE TITLE
Use Splinter for functional testing

### ISSUE THREAD

**Issue by gameFace22** [Hackademic/hackademic#135]
Use of Splinter over Selenium would be an advantage and would lessen the work of the person doing it. It is completely my view. 
I just opened this ticket to know about others view about this and also to proceed with functional testing in Hackademic.

**Comment by pchaigno** [comment]
What is it exactly? What are the differences with Selenium?
Why do you think it would lessen the work?

**Comment by gameFace22** [comment]
It is a python module which is easy to use.
All the functions which are implemented by selenium can also be implemented using splinter.
Also it's syntax is less complicated.
http://splinter.readthedocs.org/

**Comment by pchaigno** [comment]
Is it compatible with all major browsers?

**Comment by gameFace22** [comment]
Chromium,Mozilla
Enough,right?

**Comment by pchaigno** [comment]
Nothing for IE, Safari and Opera?

**Comment by gameFace22** [comment]
It does.
But is form of remote drivers which can be derived from selenium.
Also it has support for headless drivers like phasntomjs and django support.

**Comment by lucif3rr** [comment]
In the first look, Splinter looks good and easy but do we have any particular reason/advantage if we move from Selenium to splinter ?
