### ISSUE TITLE
Anyone can be an Admin - Critical Security Issue

### ISSUE THREAD

**Issue by NullArgument** [Hackademic/hackademic#139]
I have confirmed it, anyone can be an admin with just a simple POST request,

You can try it yourself, log out and make a request like this:
![oh](https://cloud.githubusercontent.com/assets/8127545/6347261/1bbcfa66-bc1f-11e4-91a0-7b48b36ea8c7.jpg)

A user "test" will be added with admin privileges.
I'll fix this ASAP.

**Comment by northdpole** [comment]
after this line https://github.com/Hackademic/hackademic/blob/next-dev/admin/controller/class.HackademicBackendController.php#L46
we need to add a die (and after the next redirection 7 lines after that.

There was an open issue to fix this before gsoc last year and someone fixed it but apparently they missed a few.

**Comment by NullArgument** [comment]
Fixed in ced5739eab16e7d4e2d7636ae99930de51617860
But I think that similar vulnerabilities still exist, I'll keep you informed.

**Comment by northdpole** [comment]
lol, check my commit above :p

**Comment by NullArgument** [comment]
@northdpole Yep, i saw your commit, I haven't tested it yet, I just added my commit also just in case :P

**Comment by NullArgument** [comment]
@northdpole Ok, i tested your commit, your solution works fine ;)

**Comment by northdpole** [comment]
good, merging onto next-dev then

**Comment by NullArgument** [comment]
@northdpole UPDATE: I found something, your solution works for users that are not logged-in,
but if i copy the "not_the_cookie_you_are_looking_for" value of a logged in student user then the vulnerability still applies.

So now we can change the Issue title to "Any student can be an Admin" :P

**Comment by northdpole** [comment]
I'll add a check for isadmin

**Comment by NullArgument** [comment]
@northdpole Ok, fixed this time.
