### ISSUE TITLE
Installation Error in db queries

### ISSUE THREAD

**Issue by antonis-manaras** [Hackademic/hackademic#152]
![screen shot 2015-05-20 at 3 40 03 pm](https://cloud.githubusercontent.com/assets/5331178/7728615/8e2d0526-ff10-11e4-8326-53cdd248a0ef.png)

**Comment by pchaigno** [comment]
On branch `next-dev`.

**Comment by kbartek7** [comment]
Problem appears becouse in file db.sql in insertion into "challenges" 16th line of values has semicolon inside. Algoryth in database.php splits queries based on semicolons. I can remove that semicolon, or we have to come up with other split algorithm.

**Comment by pchaigno** [comment]
@kbartek7 You mean [this line](https://github.com/Hackademic/hackademic/blob/next-dev/installation/sql/db.sql#L16)??

**Comment by kbartek7** [comment]
of course not. <a href="https://github.com/Hackademic/hackademic/blob/next-dev/installation/sql/db.sql#L81">this line</a>

**Comment by pchaigno** [comment]
Okay, thanks!

I don't understand why we have that algorithm. Couldn't we just import the whole file?

/cc @northdpole

**Comment by northdpole** [comment]
We could, it's legacy that nobody changed, I worked yesterday on a script to dump the database in a set of pdo parameterized queries which could be used for the installation.

( exams this week, will push the result next time I have a couple of free hours)

**Comment by pchaigno** [comment]
> I worked yesterday on a script to dump the database in a set of pdo parameterized queries which could be used for the installation.

Awesome!

**Comment by northdpole** [comment]
fixed in 5a5dd509561d49ac4c9101dbd19517ae962c4179
