### ISSUE TITLE
You guys still havn't added the install instructions that I wrote for you.

### ISSUE THREAD

**Issue by kurtcoke** [Hackademic/hackademic#166]
You guys still havn't added the install instructions that I wrote for you.
And you close the tickets that I open about posting my instructions.

**Comment by a0xnirudh** [comment]
Where is the pull request that you gave to update the install instructions? Also as a part of Summer code sprint that is going now, there will be some differences in the way we are going to install hackademic from now on. So your instructions might be wrong in those cases and which could be the reason why we closed the issue.

**Comment by northdpole** [comment]
@kurtcoke really sorry if we missed a contribution, with a quick search I couldn't find any pull requests with installation instructions all I could find is issues #165 and #153. Could you please open a pull request for next-dev? It will be merged within the day

**Comment by pchaigno** [comment]
@kurtcoke I explained why I closed it and, of course, if I got anything wrong, you can reopen it ;)
Can I close this one? :-)

**Comment by kurtcoke** [comment]
You guys dont understand docker. Dont close my tickets. Answer my question. How does docker add to security?

**Comment by awailly** [comment]
This thread does not reference anything useful for the project and in only aimed at spending time. I suggest to close it now, and if needed @kurtcoke should post a proper ticket with a pull request number.

**Comment by pchaigno** [comment]
I sent you an email on your OWASP email address. I already answered your question in the other issue. I'm going to close this now as I think we've answered your initial question ;)
