### ISSUE TITLE
Python docker module installation not done in install.py

### ISSUE THREAD

**Issue by TUArjun** [Hackademic/hackademic#194]
Issue :

When cloning the hackedemic a0xinirudh/docker branch and trying to run container_daemon.py for the first time after successfully executing install.py, the following error is encountered.

```
user@user ~/test/hackademic: python install.py 
[+] Docker has successfully installed.
[+] Now Pulling Image. This could take sometime. Please wait..
[+] Installing Docker and necessary supporting plugins
[+] This could take some time. Please wait ...
[+] Building and Configuring Docker
[+] Installation is Successful. Happy hacking !
```

``` 
user@user ~/test/hackademic: python container_daemon.py 
Traceback (most recent call last):
  File "container_daemon.py", line 12, in <module>
    from docker import Client
ImportError: No module named docker
```

Solution identified:

Upon looking through the install.py python script, It was found that there was indeed no installation command there for the docker module for python. Thus this issue can be rectified by just adding an installation candidate for the same.

**Comment by a0xnirudh** [comment]
Yea, it seems I forgot to do this in the [install.py.](https://github.com/Hackademic/hackademic/blob/a0xnirudh/docker/ContainerManager/install.py) @TUArjun can you fix it and give a pull ?
