### ISSUE TITLE
Fatal error: Cannot unset $this in C:\xampp\htdocs\hackademic-next\installation\install.php

### ISSUE THREAD

**Issue by jetweelim** [Hackademic/hackademic#239]
Hackademic installation error: 

Fatal error: Cannot unset $this in C:\xampp\htdocs\hackademic-next\installation\install.php on line 457

i have install XAMPP into my localhost for Hackademic, then try to run the install php file.
i am using PHP 7.2

many thanks in advance.

**Comment by pdgrimm** [comment]
Did you figure this out?

**Comment by HackityAnn** [comment]
Same as 241 (although older):
One of the older issues is how to get hackademic working with php7, that has not been picked up yet. So it does not work with php7, you need to purge php and reinstall a lower version.

On Ubuntu it was easiest to do:
sudo apt-get purge 'php*'
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php5.6 libapache2-mod-php5.6 php5.6-mysql

**Comment by northdpole** [comment]
hey both, this project hasn't had any activity in more than 3 years, parts of it more than 5 or 6.
i think we can consider it abandoned by now.

if you're interested in security labs i'd suggest heading over to https://github.com/bkimminich/juice-shop
