### ISSUE TITLE
Issues with Ranking Page

### ISSUE THREAD

**Issue by Bhanudev** [Hackademic/hackademic#82]
Issue 1:

Solving the same challenge many times increases the score and number of challenges cleared.

Issues 2:

When the ranking page is opened, only the ranking of first user is shown. Rankings of all the users is shown only when the search button (with 'Global' class selected) is clicked.The global class has to be made as default class.

**Comment by gameFace22** [comment]
@northdpole Once we make Global class as default,this issue can be closed.
