### ISSUE TITLE
Delete installation directory after the platform has been installed

### ISSUE THREAD

**Issue by northdpole** [Hackademic/hackademic#86]
It's not crucial but a good security practice to delete the installation directory once the platform has been installed

**Comment by SiegWahrheit** [comment]
The problem that i have is that i got this Delete function
https://github.com/SiegWahrheit/Removeinstallation-1
and it's working fine when i run it in the installer.php(in installer directory) but it runs too early(before the installation is completed and it's ruinning the following actions)
but when i attempt to run it in class.MainLoginController.php (in controller directory)  just when the user is login it doesn't delete the files.

**Comment by northdpole** [comment]
put it in the init.php file

**Comment by northdpole** [comment]
assigned to @SiegWahrheit, awaiting pull request

**Comment by F0x7r0t** [comment]
@SiegWahrheit do let me know if you can't do a pull request anytime soon. I will do it :)
